using System.IO;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;

public static class WordReportBuilder
{
    public static byte[] BuildPhenoAgeReport(PhenoAge.Inputs input, PhenoAge.Result result)
    {
        using var ms = new MemoryStream();

        using (var doc = WordprocessingDocument.Create(ms, WordprocessingDocumentType.Document, true))
        {
            var mainPart = doc.AddMainDocumentPart();
            mainPart.Document = new Document(new Body());
            var body = mainPart.Document.Body!;

            // Title
            body.Append(ParagraphOf("Phenotypic Age Report", bold: true, fontSizeHalfPoints: 40));
            body.Append(ParagraphOf("Generated by ReportAPI", italic: true));

            body.Append(new Paragraph(new Run(new Break())));

            // Summary
            body.Append(ParagraphOf("Summary", bold: true, fontSizeHalfPoints: 32));
            body.Append(ParagraphOf($"Phenotypic Age (years): {result.PhenotypicAgeYears:F1}", bold: true));
            body.Append(ParagraphOf($"10-year Mortality Risk: {result.Mortality10Yr:P2}"));
            body.Append(ParagraphOf($"Model Version: phenoage-levine-2018-v1"));

            body.Append(new Paragraph(new Run(new Break())));

            // Inputs table
            body.Append(ParagraphOf("Inputs", bold: true, fontSizeHalfPoints: 32));
            body.Append(BuildTwoColumnTable(
                ("Chronological Age (years)", input.ChronologicalAgeYears.ToString("F1")),
                ("Albumin (g/dL)", input.Albumin_g_dL.ToString("F2")),
                ("Creatinine (mg/dL)", input.Creatinine_mg_dL.ToString("F2")),
                ("Glucose (mg/dL)", input.Glucose_mg_dL.ToString("F1")),
                ("CRP (mg/L)", input.CRP_mg_L.ToString("F2")),
                ("Lymphocytes (%)", input.LymphocytePercent.ToString("F1")),
                ("MCV (fL)", input.MCV_fL.ToString("F1")),
                ("RDW (%)", input.RDW_percent.ToString("F1")),
                ("Alk Phos (U/L)", input.AlkalinePhosphatase_U_L.ToString("F1")),
                ("WBC (10^3/µL)", input.WBC_10e3_per_uL.ToString("F2"))
            ));

            body.Append(new Paragraph(new Run(new Break())));

            // Optional: Interpretation section
            body.Append(ParagraphOf("Notes", bold: true, fontSizeHalfPoints: 32));
            body.Append(ParagraphOf("This report is generated from the PhenoAge algorithm using provided inputs."));

            mainPart.Document.Save();
        }

        return ms.ToArray();
    }

    private static Paragraph ParagraphOf(string text, bool bold = false, bool italic = false, int fontSizeHalfPoints = 24)
    {
        var runProps = new RunProperties();
        if (bold) runProps.Append(new Bold());
        if (italic) runProps.Append(new Italic());
        runProps.Append(new FontSize { Val = fontSizeHalfPoints.ToString() }); // half-points

        var run = new Run(runProps, new Text(text) { Space = SpaceProcessingModeValues.Preserve });
        return new Paragraph(run);
    }

    private static Table BuildTwoColumnTable(params (string label, string value)[] rows)
    {
        var table = new Table();

        // Simple table borders (Word needs this to look sane)
        table.AppendChild(new TableProperties(
            new TableBorders(
                new TopBorder { Val = BorderValues.Single, Size = 6 },
                new BottomBorder { Val = BorderValues.Single, Size = 6 },
                new LeftBorder { Val = BorderValues.Single, Size = 6 },
                new RightBorder { Val = BorderValues.Single, Size = 6 },
                new InsideHorizontalBorder { Val = BorderValues.Single, Size = 6 },
                new InsideVerticalBorder { Val = BorderValues.Single, Size = 6 }
            )
        ));

        foreach (var (label, value) in rows)
        {
            var tr = new TableRow();
            tr.Append(
                Cell(label, bold: true),
                Cell(value)
            );
            table.Append(tr);
        }

        return table;
    }

    private static TableCell Cell(string text, bool bold = false)
    {
        var runProps = new RunProperties();
        if (bold) runProps.Append(new Bold());

        var p = new Paragraph(new Run(runProps, new Text(text) { Space = SpaceProcessingModeValues.Preserve }));
        return new TableCell(p);
    }
}
